name       : rocksndiamonds
version    : 4.3.4.0
release    : 2
source     :
    - https://www.artsoft.org/RELEASES/linux/rocksndiamonds/rocksndiamonds-4.3.4.0-linux.tar.gz : 81d815e1296c041ed94ae9777397f40fdf5d13ecb5b375202af96a3119904ad7
homepage   : https://www.artsoft.org/rocksndiamonds/
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : Underground digging game
description: |
    Rocks 'n' Diamonds is a action puzzle game similiar to Boulderdash with lots of levels where you have to navigate a maze of dirt, rocks, enemies and quicksand, while collecting gems and making it safely to the exit. Be careful not to get crushed by falling rocks or killed by an enemy.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
rundeps    :
    - libmodplug
setup      : |
    # Remove unnecessary patch files.
    rm -rf levels/Tutorials/*/*.orig
build      : |
    %make BASE_PATH=/usr/share/rocksndiamonds
install    : |
    install -Dm00755 rocksndiamonds -t $installdir/usr/bin
    install -dm00644 $installdir/usr/share/doc/rocksndiamonds
    install -dm00644 $installdir/usr/share/rocksndiamonds
    cp -R {graphics,levels,sounds,music} $installdir/usr/share/rocksndiamonds
    cp -R docs/elements -t $installdir/usr/share/doc/rocksndiamonds
    install -Dm00644 $pkgfiles/rocksndiamonds.desktop -t $installdir/usr/share/applications
    install -Dm00644 build-projects/android/app/src/main/res/mipmap-hdpi/ic_launcher.png $installdir/usr/share/pixmaps/rocksndiamonds.png
